### PR TITLE
page contents box [techniques & understanding , index & about, base.css] 

### PR DESCRIPTION
**Pull request by shawna-slh**
might need ```<div class="default-grid with-gap leftcol">``` as in, for example: view-source:https://draft-wcag-redesign.netlify.app/techniques/aria/aria1

### CODE REVIEW

**Comment by michael-n-cooper** [comment]
This can be done but there is coding to make sure it's outputting current info.

**Comment by shawna-slh** [comment]
@SteveALee are you able to take this one? I think it needs some class names to work...

**Comment by SteveALee** [comment]
Yes, I have a partial fix on my machine.

**Comment by SteveALee** [comment]
I updated the 2 index pages and 2 about pages.

Note that the markup has changed for the side bar and you'll need to sync all the other pages.

**Comment by SteveALee** [comment]
the heading text is to big

**Comment by SteveALee** [comment]
@michael-n-cooper Here's the details for how the Page contents markup changed after feedback from APG

was
````html
         <aside class="box nav-hack sidebar standalone-resource__sidebar ">
            <nav>
               <header class="box-h ">Page Contents</header>
               <div class="box-i">
                  <ul>
                    ...
                  </ul>
               </div>
            </nav>
         </aside>
````

```html
         <nav class="box nav-hack sidebar standalone-resource__sidebar" aria-labelledby="sidebar-header">
            <h2 id="sidebar-header" class="box-h ">Page Contents</h2>
            <div class="box-i">
               <ul>
                    ...
               </ul>
            </div>
         </nav>
```

**Comment by shawna-slh** [comment]
These page contents boxes are ready to deploy.

Note that at some point, I do want us to improve the [Understanding Index page structure](https://github.com/w3c/wcag-redesign/issues/6) which will be reflected in the Page Contents; however, we might not get to that before first roll-out.

**Comment by shawna-slh** [comment]
> Note that at some point, I do want us to improve the https://github.com/w3c/wcag-redesign/issues/6 which will be reflected in the Page Contents; however, we might not get to that before first roll-out.

If we don't get to that in the first iteration, it would be good to include in the page contents box h2s and h3s. We do have that in some WAI pages. However, might need to tweak for this design. Hopefully we can just improve the headings instead.

**Comment by michael-n-cooper** [comment]
fixes #1

**Pull request closed without merging**
