### PR TITLE
nav bar bug -- adjust pager css

### PR DESCRIPTION
**Pull request by SteveALee**

### CODE REVIEW

**Comment by SteveALee** [comment]
I noticed a couple of other possible issues

- the Understanding current guideline is highligted as if it is a tab  - the suppl pager doesn;t do that
- techniques pager doesn;t seem to be working how I might expect

**Review by shawna-slh — APPROVED** [review]

**Comment by shawna-slh** [comment]
Hey @SteveALee I can't tell if there are still open issues, or if this is ready for Michael?

From my quick QA, the pager now gets the scrollbar when need on all the Understanding pages.

In [issue 2](https://github.com/w3c/wcag-redesign/issues/2#issuecomment-1227531764) you said:
> I saw the scrollbar whenever hover ove the pager so suspect a width bug somewhere

I haven't been able to reproduce that in Vivaldi or Firefox. Is it fixed or still an issue? If still an issue, would you be comfortable with that being milestone level 4 that we might not get done before roll out?

from above:
> techniques pager doesn't seem to be working at all

We decided not to implement a "pager" in the techniques, since users pretty much never "walk" the techniques. So for now that area has only "All Techniques". For later enhancement we might [add the categories](https://github.com/w3c/wcag-redesign/issues/8), but that is very low priority for later.

> the current guideline in the pager was highlighted as if it is a tab. needed to remove the active state,

looks to me like you go that fixed!?!

**Comment by SteveALee** [comment]
Left assigned to me due to scrollbar issue I saw. But as you cannot repo I'm good.

I'd did a global fix for pager highlight, even though not strictly required as I left details for fix in source.

Assigning over to Michael.

**Comment by SteveALee** [comment]
Oops github mobile app doesn't let me assign

@michael-n-cooper sorry for large difference due to "active" change. Hopefully you can do a different from before.

**Pull request closed without merging**
